### ISSUE TITLE
Missing dependency typing_extensions

### ISSUE THREAD

**Issue by alxlive** [7sDream/torrent_parser#11]
When I tried to import the torrent parser module, I got the following error:

`ModuleNotFoundError: No module named 'typing_extensions' `

I fixed it by running `pip install typing_extensions`. You probably need to add it as a dependency.

**Comment by 7sDream** [comment]
It shouldn't be a required dependency, maybe I forgot to remove the `import` code after experimenting with some features.

I'll check this tonight, thanks for your report.

**Comment by junwoo091400** [comment]
Still happening :) I will create PR for this!

**Comment by 7sDream** [comment]
PR published in version `v0.4.1`.
