### ISSUE TITLE
v2 Torrent supported？

### ISSUE THREAD

**Issue by daomengRen** [7sDream/torrent_parser#9]
hello,
use v2 torrent,
Getting "Fail to decode string at pos 145 using encoding utf-8 when parser field "pieces root", maybe it is an hash field. You can use self.hash_field("pieces root") to let it be treated as hash value, so this error may disappear" at torrent file parse.

Example torrent file:
https://libtorrent.org/bittorrent-v2-test.torrent

**Comment by 7sDream** [comment]
Could you try way 2 in [this comment](https://github.com/7sDream/torrent_parser/issues/4#issuecomment-399634500) and check if it works?

with argument: `hash_fields={"pieces root": (32, False)}`

**Comment by daomengRen** [comment]
I try `data = tp.parse_torrent_file(str, hash_fields={"pieces root": (32, False)})`， Getting “torrent_parser.InvalidTorrentDataException: Fail to decode string at pos 1359 using encoding utf-8”

**Comment by 7sDream** [comment]
It seems this v2 file has a `piece layers` dict whose key and value are all hash bytes.

Current `hash_fields` argument can't specify entrie dict.

For now, **if you don't care about `piece layers` values**, you can add `errors="replace"` to make parse success:

```python
data = tp.parse_torrent_file(
    "bittorrent-v2-test.torrent",
    hash_fields={
        "pieces root": (32, False),
    },
    errors="replace",
)
```

But if you edit `data` and write back to file, the content of `piece layers` will be **incorrect**.

I will publish a new version to solve this issue.

**Comment by daomengRen** [comment]
Looking forward to new version，If I only edit the content except the piece layers, will I get an error when writing to the file?

**Comment by 7sDream** [comment]
No error will be raise if you write back to file, it is the **file content is incorrect**.

Because `error="replace"` argument of parse step replaced invalid utf8 bytes in `piece layers` with [`Unicode Replacement Character`](https://unicode-table.com/en/FFFD/). In encode/write step, we can't restore origin bytes.

**Comment by 7sDream** [comment]
[v0.4.0](https://github.com/7sDream/torrent_parser/compare/v0.3.0...v0.4.0) just published.

Please try it with `tp.parse_torrent_file("bittorrent-v2-test.torrent")` without any other argument. In theory you should be able to successfully parse the file.

Feel free to continue this thread if you meet any issue when using the new version.

**Comment by daomengRen** [comment]
It's working fine, thank you

**Comment by 7sDream** [comment]
That's fine, then I'll close the issue.

If there are any subsequent issue, you can open a new one.
